- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
- suomen-vaylat-app/src/translations/en.tsx
- suomen-vaylat-app/src/translations/fi.tsx
- suomen-vaylat-app/src/translations/sv.tsx
Fix error that causes when adding new theme and translation not found
> Fix theme translation not found error

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModal.jsx
- suomen-vaylat-app/src/components/layout/Content.tsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/share-web-site/ShareWebSitePopup.jsx
Replace modals to own modal component
> Use own modals

- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomBar.jsx
- suomen-vaylat-app/src/translations/fi.tsx
- suomen-vaylat-app/src/translations/sv.tsx
Fix tooltip on ZoomMenu component
https://extranet.vayla.fi/jira/browse/SV-228
> SV 228 set label on tooltip

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/Layers.jsx
https://extranet.vayla.fi/jira/browse/SV-225
> SV-225 Fix bug on layers component

- suomen-vaylat-app/src/components/share-web-site/HandleSharedWebSiteLink.jsx
- suomen-vaylat-app/src/components/share-web-site/ShareWebSitePopup.jsx
Fix theme sharing link handling when theme has large amount default layers.
https://extranet.vayla.fi/jira/browse/SV-227
> Fix theme sharing

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/metadata-modal/MetadataModal.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- Added MetadataModal as global Modal component
- Minor styling fixes
- Clean code
> Implement global MetadataModal

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerList.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
https://extranet.vayla.fi/jira/browse/SV-235
> SV-235 Fix mobile bug on firefox android

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerList.jsx
https://extranet.vayla.fi/jira/browse/SV-238
> SV-238 Set layer subgroups alphabetically on the front end side

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- using NLSFI geocoding API to get address search results
- added type and region also to show search results list
https://extranet.vayla.fi/jira/browse/SV-201
> Change search use NLSFI geocoding api and show also type and region for address search

- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/share-web-site/ShareLinkButtons.jsx
https://extranet.vayla.fi/jira/browse/SV-243
> Update header mobile view

- suomen-vaylat-app/src/components/search/Search.jsx
https://extranet.vayla.fi/jira/browse/SV-244
> SV-244 search UI fixes

- suomen-vaylat-app/src/translations/fi.json
https://extranet.vayla.fi/jira/browse/SV-245
> SV-245 Updated app info texts

- suomen-vaylat-app/src/translations/fi.json
https://extranet.vayla.fi/jira/browse/SV-245
> SV-245 Set updated texts to app version info

- suomen-vaylat-app/src/components/action-button/ActionButtons.jsx
Fix action button exit animations
> Fix action buttons animations

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModalContent.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
https://extranet.vayla.fi/jira/browse/SV-241
> SV-241 Update app info with links

- suomen-vaylat-app/src/components/infobox/GFIPopup.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/legend/Legend.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomBar.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomBarCircle.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomMenu.jsx
Fixed Zoombar styling according UI-layouts.
> Improve zoombar styling on mobile

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/search/AddressSearch.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Fix Search.jsx styling according UI-layouts
- Add animations for Search
- Add proper translations
- Clean code
> Improve search component

- suomen-vaylat-app/src/components/zoom-features/ZoomMenu.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.tsx
- suomen-vaylat-app/src/utils/rpcUtil.jsx
- Open Legend when Theme group is selected.
- Close Legend when user closes Theme group.
> Open legend when theme map is selected

- suomen-vaylat-app/src/components/infobox/FormattedGFI.jsx
GFI now not show rows where value is empty.
> Not show rows where GFI response property value is empty

- suomen-vaylat-app/src/components/dialog/MapLayersDialog.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/search/MetadataSearch.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMSearch.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
* Refactored address search
* Refactored road search
* New metadata search
* Search componen animated
> Refactor search and implement metadata search

- suomen-vaylat-app/src/components/circle-button/CircleButton.jsx
- suomen-vaylat-app/src/components/dialog/MapLayersDialog.jsx
- suomen-vaylat-app/src/components/language-selector/LanguageSelector.tsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/legend/Legend.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/share-web-site/ShareLinkButtons.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomBar.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomMenu.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Added global CircleButton.jsx component with tooltip feature
- Fixed header button alignment
- Cleaned code
- Added blur effects for generic look
- Added translations for Search.jsx tooltip
> Add general circle button and tooltips

- suomen-vaylat-app/src/components/circle-button/CircleButton.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- Add CircleButton.jsx for drawing tools buttons including tooltips
- Clean code
- Add checks for channel events to prevent channel undefined errors.
> Add CircleButtons for drawing tools

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/scalebar/ScaleBar.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
> Implement scalebar

- suomen-vaylat-app/src/App.tsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/utils/rpcUtil.jsx
- Fixed / Added fullscreen features to support all browsers
> Fix fullscreen feature to support all browsers

- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMSearch.jsx
- Add hide dropdown arrow to VKM search
- Set search method to default when search is closed
- Reset error messages when new search is made
> Add hide dropdown arror to vkm search

- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMRoadSearch.jsx
- suomen-vaylat-app/src/components/search/VKMSearchStyles.jsx
- suomen-vaylat-app/src/components/search/VKMTrackSearch.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
New VKM track search.
https://extranet.vayla.fi/jira/browse/SV-259
> VKM track search

- suomen-vaylat-app/src/components/infobox/GFIPopup.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/legend/Legend.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/Layer.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMRoadSearch.jsx
- suomen-vaylat-app/src/components/search/VKMTrackSearch.jsx
- suomen-vaylat-app/src/components/share-web-site/HandleSharedWebSiteLink.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
* Show all search same kind text "No results found for __ search"
* Search results delete works same way now in all searches
* Search result features remove only remove search results (not gfi or drawing)
* Clear map features always when quering new search
* Fixed FF Android phone problem in track search
* Fixed also legend rendering (now not render so much times than previously)
> Search improvements

- suomen-vaylat-app/src/components/layout/Header.jsx
https://extranet.vayla.fi/jira/browse/SV-273
> Clear url when pressing sv main logo

- suomen-vaylat-app/src/components/infobox/FormattedGFI.jsx
- suomen-vaylat-app/src/components/menus/selected-layers/SelectedLayers.jsx
https://extranet.vayla.fi/jira/browse/SV-293
> Fix gfi js trim is not function error

- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
Added taitorakennerekisteri description in layer group menu
> SV-Update-layer-group-texts

- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
https://extranet.vayla.fi/jira/browse/SV-273
> SV-273 Fix suomen vaylat button functionality

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/Layer.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerDownloadLinkButton.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerDownloadLinkButtonModal.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.tsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
https://extranet.vayla.fi/jira/browse/SV-309
> Layer download link button

- suomen-vaylat-app/src/components/dialog/WarningDialog.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/views/Views.jsx
- suomen-vaylat-app/src/components/warning/WarningModalContent.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.tsx
* Add general warning modal to handle all warning / alert messages
* Minor styling fixes
> Improve warning functionality

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/Layer.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerDownloadLinkButtonModal.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
- suomen-vaylat-app/src/components/search/RoadSearch.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMRoadSearch.jsx
- suomen-vaylat-app/src/components/views/Views.jsx
* Improved road search functionality for more user friendly search experience.
* Minor styling fixes
> Improve road search

- suomen-vaylat-app/src/components/search/RoadSearch.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMRoadSearch.jsx
* Fix road search issue when distance field is used and search icon is pressed.
> Fix road search usability issue

- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/search/VKMRoadSearch.jsx
- suomen-vaylat-app/src/components/search/VKMTrackSearch.jsx
* Improved VKM track search for more user friendly and clearer use
> Implement improvements

- suomen-vaylat-app/src/components/layout/Header.jsx
https://extranet.vayla.fi/jira/browse/SV-318
> Move start state selected layers selecting after than group resetting

- suomen-vaylat-app/src/components/search/Search.jsx
Track number is string format so parseInt removed for this field
> Fix track search

- suomen-vaylat-app/src/components/search/Search.jsx
Remove always road feature when handling search response.
> Road search: remove map features also when error come

- suomen-vaylat-app/src/components/checkbox/CheckBox.jsx
- suomen-vaylat-app/src/components/dialog/MapLayersDialog.jsx
- suomen-vaylat-app/src/components/gfi/FormattedGFI.jsx
- suomen-vaylat-app/src/components/gfi/GFIDownload.jsx
- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/gfi/GfiDownloadMenu.jsx
- suomen-vaylat-app/src/components/gfi/GfiToolsMenu.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/loader/CircleLoader.jsx
- suomen-vaylat-app/src/components/loader/SvLoader.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/modals/ModalListItem.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/views/Views.jsx
- suomen-vaylat-app/src/components/zoom-features/ZoomBar.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.tsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
* Added GFI Download selection menu to GFI Popup.
* Added Downloads modal and Downloads button to Menu bar.
* Minor styling fixes.
* Added Translations.
* Added Checkbox button component.
* Renamed components
> Implement gfi download functionality

- suomen-vaylat-app/src/components/gfi/GFIDownload.jsx
- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/modals/ModalListItem.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
* Add error handling if GFI Download includes errors.
* Add translations.
* Minor styling fixes.
* Change rendering methods.
> Fix gfi download functionality

- suomen-vaylat-app/src/components/announcements-modal/AnnouncementsModal.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerList.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/utils/rpcUtil.jsx
Annoucements server response has different than 2.7.1 release.
Make announcement modal to work new data structure (localization) --> changed response modifying to rpcUtil
Also make LayerGroup and LayerList to work if group has no name.
> Make announcements to work Oskari release 2.8.0

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerList.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
* Fix group order to alphabetical and groups layers check to recursive
* Group description read more style fix
* Group description read more style fix and added group description read from geoportal
> Fix oskari 2.8.0 changes

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/Header.jsx
- Remove marker on map when user closes GFI modal
- Clear VKM data when user closes GFI modal
> Remove marker and VKM data on modal close

- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- Add tooltip direction to circle buttons
> Fix wrong tooltips on drawing tools

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
- set zoom to theme's default layers minimum zoom level when user selects a theme
> Theme default layers min zoom

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- Fix bug where modal resizing broke at 50% width
- Fix dragging bug where modal could not be moved vertically
- Remove naimations for now as they don't work properly with the current implementation of the modal
- Modal now resizes correctly to the same width and height it was before maximizing the modal window
> Fix modal resize and dragging bugs

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModalContent.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Add terms of use to datasources
- Add an additional datasource
> Add terms of use 

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModalContent.jsx
- suomen-vaylat-app/src/components/modals/Modal.jsx
- Check if mobile and scale modal accordingly
> Fix modal responsiveness

- suomen-vaylat-app/src/components/modals/Modal.jsx
- suomen-vaylat-app/src/components/scalebar/ScaleBar.jsx
- Change cursor style on zoombar hover
- Disable modal dragging on mobile so GFIPopup can no longer be dragged
> Minor usability improvements

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModalContent.jsx
- add hamburger menu for mobile users to improve responsiveness
> Add seperate mobile view for info modal

- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- restyle layout
- show instructions if vkm info is missing data
- location info is open by default
> Restyle location info 

- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/gfi/GfiTabContent.jsx
- suomen-vaylat-app/src/components/gfi/GfiToolsMenu.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.tsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Add possibility to get more than 100 features
- Use SV Loader when getting more features
- Default to 100 items per page
- Add necessary states to slices
WIP
TO DO:
-fix handling over 100 results when maakuntavalinta was clicked on a road
- localization
- minor improvements overall
> Handle over 100 features

- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/user-guide-modal/UserGuideModalContent.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Change icons
- Change localization strings
> Change icons to represent drawing instead of measuring

- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- change order of StopDrawingRequests to fix geometry removal
> Fix geometries not removing correctly

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/user-guide-modal/UserGuideModalContent.jsx
- suomen-vaylat-app/src/components/user-guide-modal/UserGuideTabs.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- add new sections
- change styling
> Update user guide

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerGroup.jsx
> Fix switch bug on groups with subgroups

- suomen-vaylat-app/src/components/circle-button/CircleButton.jsx
- suomen-vaylat-app/src/components/gfi/GfiToolsMenu.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/layout/Header.jsx
- suomen-vaylat-app/src/components/layout/menu-bar/MenuBar.jsx
- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
- suomen-vaylat-app/src/state/slices/uiSlice.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- Add new drawing tool: marker
- Add different shapes for markers
- Allow deleting either a single marker or all of them
- Fix bugs where all markers were deleted when for example closing GFIPopup
- Allow adding text labels for markers
- Localization
Possible future improvements:
- Animations?
> Add markers

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
- suomen-vaylat-app/src/components/share-web-site/HandleSharedWebSiteLink.jsx
- fix bug where themegroups default layers were not visible when sharing theme via a link
> Fix theme group bug when sharing theme

- suomen-vaylat-app/src/components/zoom-features/ZoomBar.jsx
- suomen-vaylat-app/src/utils/rpcUtil.jsx
- open the whole zoombar when choosing a theme
> Legend size too small when selecting a theme

- suomen-vaylat-app/src/components/menus/selected-layers/SelectedLayers.jsx
- fixes backgroundmaps not grouping properly on all layers
> Backgroundmap grouping recursively

- suomen-vaylat-app/src/components/views/Views.jsx
removing all saved geometries removes them from the map
> Fix removed geometries staying on the map

- suomen-vaylat-app/src/components/layout/Header.jsx
- app logo click resets activegeometries on saved views modal
> Reset geometries on logo click

- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/gfi/GfiDownloadMenu.jsx
- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- suomen-vaylat-app/src/components/search/Search.jsx
- suomen-vaylat-app/src/components/toasts/TipToast.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- take websocket into use
- fix wrong coordinates on one instance
- fix bug where app crashed if downloadmenu was open and user clicked on the map
> Use web socket on downloads

- suomen-vaylat-app/src/components/legend/Legend.jsx
- add min and max width so legend scales according to it's content
> Fix legend text overflow

- suomen-vaylat-app/src/utils/rpcUtil.jsx
- switching themegroups closes former theme layers and subtheme layers recursively
> Switching theme group close subtheme layers

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/Layer.jsx
- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/ThemeLayerList.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- add descriptions for some of the theme groups that did not have any
- improve semantics
- use bigger font size so text is easier to read
- remove unnecessary media queries
> Add themegroup descriptions

- suomen-vaylat-app/src/components/app-info-modal/AppInfoModalContent.jsx
- suomen-vaylat-app/src/components/gfi/GFIPopup.jsx
- suomen-vaylat-app/src/components/gfi/GfiTabContentItem.jsx
- suomen-vaylat-app/src/components/metadata-modal/Components/OnlineResources.jsx
- suomen-vaylat-app/src/utils/validUrlUtil.js
- add util function to check if a url is valid
- add links to GFIPopup
- open links in a new window throughout the app
> GFI url's to links & open links in a new window

- suomen-vaylat-app/src/components/menus/hierarchical-layerlist/LayerList.jsx
- add temporary id check for tierekisteri until it is removed
> Make tierekisteri the lowest element on the list

- suomen-vaylat-app/src/components/menus/selected-layers/SelectedLayer.jsx
- suomen-vaylat-app/src/components/menus/selected-layers/SelectedLayers.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
- suomen-vaylat-app/src/utils/rpcUtil.jsx
- change opacity icon render logic to be faster
- add selectedLayersByType in which grouping of layers is done
- fixes background map opacity toggling not working when backgroundmap subgroups are selected
> Add selected layers grouping by type

- suomen-vaylat-app/src/components/user-guide-modal/UserGuideModalContent.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- add geometry saving instructions to userguide
- change modal name
> Add geometry saving to user guide

- suomen-vaylat-app/src/components/layout/Content.jsx
- suomen-vaylat-app/src/state/slices/rpcSlice.jsx
Make download work better on AWS:
- when reconnecting websocket, ask download statuses again
> Websocket download redis status messages

- suomen-vaylat-app/src/components/gfi/GfiToolsMenu.jsx
- suomen-vaylat-app/src/components/measurement-tools/DrawingTools.jsx
- suomen-vaylat-app/src/components/published-map/PublishedMap.jsx
- fix gfitoolsmenu animation loading state gets stuck on true
- move drawingtool eventhandler to published map
> Fix gfitools loading animation stuck 

- suomen-vaylat-app/src/components/gfi/GfiTabContent.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
add text before id on gfi listview to make it more clear what the number (id) means
> GFI list view text explaining ids

- suomen-vaylat-app/package-lock.json
- suomen-vaylat-app/src/components/dialog/MapLayersDialog.jsx
- suomen-vaylat-app/src/components/user-guide-modal/UserGuideModalContent.jsx
- suomen-vaylat-app/src/components/user-guide-modal/UserGuideTabs.jsx
- suomen-vaylat-app/src/translations/en.json
- suomen-vaylat-app/src/translations/fi.json
- suomen-vaylat-app/src/translations/sv.json
- add thememaps to its own menu on userguidemodal
- minor styling changes
- translations
> Add theme menu to its own user guide section

- suomen-vaylat-app/src/components/gfi/GfiDownloadMenu.jsx
> Rename and move geopackage for downloads
